In [2]:
aa = ('aa', 1)
print(type(aa))


<class 'tuple'>


In [35]:
import numpy as np

# numpy.ndarray 任意维度
a = np.ones((5, 1))
print(type(a))
# numpy.matrix 只能是二维 
b = np.mat(a)
print(type(b))
# 相互转化
print(type(b.A))
print(a)
print(b.T)


<class 'numpy.ndarray'>
<class 'numpy.matrix'>
<class 'numpy.ndarray'>
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1. 1. 1. 1. 1.]]


In [34]:
a = np.array([[1, 1, 2, 3, 4, 1, 2, 3, 4, 5, 1, 2, 4, 2]])
s = [1, 1, 2, 3, 4, 1, 2, 3, 4, 5, 1, 2, 4, 2]
print(a > 3)
print(a < 5)
print(a * a)
# 注意行列的区别
zz = np.nonzero((a > 3) * (a < 5))
print(a.shape)
# 计算的是交集
print((a > 3) * (a < 5))
print(np.array(zz).ndim)
print(zz)
for i in zz[0]:
    print("a", i)
    c = s[i]
    print(c)


[[False False False False  True False False False  True  True False False
   True False]]
[[ True  True  True  True  True  True  True  True  True False  True  True
   True  True]]
[[ 1  1  4  9 16  1  4  9 16 25  1  4 16  4]]
(1, 14)
[[False False False False  True False False False  True False False False
   True False]]
2
(array([0, 0, 0], dtype=int32), array([ 4,  8, 12], dtype=int32))
a 0
1
a 0
1
a 0
1


In [2]:
import numpy as np
a = np.array([[1, 2, 3],
              [3, 4, 5]])
b = np.mat(a)
m, n = b.shape
sumb = np.zeros((n, 1)).T
for i in range(m):
    print(b[i, :])
    sumb += b[i, :]
print(sumb)


TypeError: only size-1 arrays can be converted to Python scalars

In [5]:
import numpy as np

lists = [1, 2, 3, 4, 5, 6]
cc = np.mat(lists).reshape(3, 2)
print(cc)
dd=np.mat(cc)
print(dd)
print(dd.A)


[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
