In [3]:
# note
aa = map(float, [1, 2, 3])
print(list(aa))


[1.0, 2.0, 3.0]


In [18]:
import numpy as np

m = 5
bb = np.mat([[1, 2, 3, 4],
             [1, 3, 2, 4],
             [3, 4, 5, 2]])
aa = np.eye(bb.shape[1])
print(aa)
print(bb + aa)
# aa[3, 3] = 2
# print(aa.I)
# dd = bb + aa
# print(dd)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,4) 