In [2]:
import numpy as np

a=np.mat([[1,2,3],
         [2,3,4]])
print(a.dtype.byteorder)
print(a.dtype.byteorder)

=
=


In [14]:
from collections import defaultdict
a=np.array([1,2])
print(a)
aa=[{1,2,3,3},'www',[2.1,2.3,4.5]]
print(aa)
dd=defaultdict(list)
dd['aa'].append(aa)
print(dd)


[1 2]
[{1, 2, 3}, 'www', [2.1, 2.3, 4.5]]
defaultdict(<class 'list'>, {'aa': [[{1, 2, 3}, 'www', [2.1, 2.3, 4.5]]]})


In [2]:
import numpy as np

p1=np.mat([[0.6,0.2],
           [0.4,0.8]])
p2=np.mat([[0.44,0.28],
          [0.56,0.72]])

a=np.dot(p2,p1)
print(a)

[[0.376 0.312]
 [0.624 0.688]]


In [40]:
import numpy as np
A=np.mat([[0,1,1,2,0,0,0],
          [1,0,1,1,1,0,0],
          [1,1,0,1,0,0,0],
          [1,1,1,0,0,0,0],
          [0,1,0,0,0,1,1],
          [0,0,0,0,1,0,1],
          [0,0,0,0,1,1,0]])
print(np.linalg.norm(A[:,0]))
print(A.T[0][:,5])
q,r=np.linalg.qr(A)
print(q)
print(r)
e=f=50
f=1
print(e)
print(f)
c=np.dot(A,A.T)
# 计算特征向量
a=np.linalg.eig(c)
print(a)
print(c)
U,Sigm,VT=np.linalg.svd(c)
print(U)
print(Sigm)
print(VT)
np.diag(U)


1.7320508075688772
[[0]]
[[ 0.          0.61237244  0.61237244  0.46662826  0.06394568 -0.08564859
   0.14433757]
 [-0.57735027 -0.40824829  0.40824829  0.20739034 -0.19183705  0.25694577
  -0.4330127 ]
 [-0.57735027  0.20412415 -0.61237244  0.46662826  0.06394568 -0.08564859
   0.14433757]
 [-0.57735027  0.20412415  0.20412415 -0.6740186   0.12789137 -0.17129718
   0.28867513]
 [-0.          0.61237244 -0.20412415 -0.25923792 -0.25578273  0.34259435
  -0.57735027]
 [-0.          0.          0.          0.         -0.66077206 -0.73657786
  -0.14433757]
 [-0.          0.          0.          0.         -0.66077206  0.4796321
   0.57735027]]
[[-1.73205081 -1.15470054 -1.15470054 -1.15470054 -0.57735027  0.
   0.        ]
 [ 0.          1.63299316  0.40824829  1.02062073 -0.40824829  0.61237244
   0.61237244]
 [ 0.          0.          1.22474487  1.02062073  0.40824829 -0.20412415
  -0.20412415]
 [ 0.          0.          0.          1.60727513  0.20739034 -0.25923792
  -0.25923792]
 [ 0

array([-6.35570283e-01, -8.57992648e-02,  2.12435745e-01,  7.25812439e-01,
       -7.71670580e-17,  5.43310740e-02, -3.64534465e-01])

In [5]:
import numpy as np

a=np.array([-8/5,4/5,-16/5,8/5])
s=np.dot(a,a.T)
print(s)
b=np.mat([[1,-2,-1],
          [2,0,1],
          [2,-4,2],
          [4,0,0]])
q,r=np.linalg.qr(b)
print(q)
print(r)

16.000000000000004
[[-0.2  0.4  0.8]
 [-0.4 -0.2 -0.4]
 [-0.4  0.8 -0.4]
 [-0.8 -0.4  0.2]]
[[-5.  2. -1.]
 [ 0. -4.  1.]
 [ 0.  0. -2.]]


In [2]:
import numpy as np

A=np.zeros((3,3))
A[2,2]=1
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]


In [13]:
b=bin(5678)
c=bin(1234)
print(c )
print(b)
print(np.power(2,4))

0b10011010010
0b1011000101110
16


In [53]:
import numpy as np
a=np.array([1,2])
b=np.array([2,3])
c=np.dot(a,b)
print(c)
d=np.multiply(1,b)
print(d)
m=np.divide(a,b)
print(m)
y=np.add(a,b)
print(y)
y=np.subtract(a,b)
print(y)
l=np.zeros((3,3))
print(l)
k=np.zeros(4)
print(k)

8
[2 3]
[0.5        0.66666667]
[3 5]
[-1 -1]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0.]


In [49]:
for i in range(1,4):
    for j in range(0,5):
        if i!=j:
            print('i',i,'j',j)
        else:
            break
    print("aaaa")


i 1 j 0
aaaa
i 2 j 0
i 2 j 1
aaaa
i 3 j 0
i 3 j 1
i 3 j 2
aaaa
